<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerT30kkf9\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerT30kkf9/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerT30kkf9.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerT30kkf9\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerT30kkf9\appProdProjectContainer([
    'container.build_hash' => 'T30kkf9',
    'container.build_id' => '6a74cf2d',
    'container.build_time' => 1764424225,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerT30kkf9');
