<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerA0ggwtc\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerA0ggwtc/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerA0ggwtc.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerA0ggwtc\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerA0ggwtc\appProdProjectContainer([
    'container.build_hash' => 'A0ggwtc',
    'container.build_id' => '62639266',
    'container.build_time' => 1765653043,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerA0ggwtc');
